version: '3.8'
services:
  neo4j:
    image: neo4j:5
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - neo4j
      - redis
    env_file:
      - .env
    command: uvicorn api.server:app --host 0.0.0.0 --port 8000 --reload

volumes:
  neo4j_data:
  redis_data:
